## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [1]:
import numpy as np

# Generate two NumPy arrays (1st array between 10 to 40 and 2nd array 220 to 250)
first_array = np.arange(10, 41)
second_array = np.arange(220, 251)

# Sum both arrays and present the result array
result_array = first_array + second_array

# Display result to verify
print("Array 1:", first_array)
print("Array 2:", second_array)
print("Result Array:", result_array)

Array 1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40]
Array 2: [220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250]
Result Array: [230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]


2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [5]:
import numpy as np

# Generate 10 rows - 7 columns two-dimensional arrays containing integers starting from 100
array_2d = np.arange(100, 100 + 10*7).reshape(10,7)

# display array to verify
array_2d

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [8]:
import numpy as np

# Generate the first array with even numbers between 1 and 50
even_array = np.arange(2, 51, 2)

# Generate the second array with odd numbers between 1 and 50
odd_array = np.arange(1, 51, 2)

# Multiply corresponding elements from both arrays
result_array = even_array * odd_array

# Display the result to verify
print("Even array:", even_array)
print("Odd array:", odd_array)
print("Result array:", result_array)


Even array: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
Odd array: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Result array: [   2   12   30   56   90  132  182  240  306  380  462  552  650  756
  870  992 1122 1260 1406 1560 1722 1892 2070 2256 2450]


4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [16]:
import numpy as np

# Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000
random_array = np.random.randint(1, 1001, size=(40, 5))

# Create a mask to filter the numbers divisible by both 2 and 5
mask = (random_array % 2 == 0) & (random_array % 5 == 0)

# Apply the mask to the random array to get the filtered result
filtered_array = random_array[mask]

# Display the original array and filtered array to verify
print("Original Array:")
print(random_array)
print("Filtered Array:")
print(filtered_array)

Original Array:
[[402 999 285 881  67]
 [615 597 321 534 296]
 [ 55 506 641 547 311]
 [154 255 373 436 960]
 [308 323 858 200 408]
 [496  62 759 687 384]
 [502 261 134 860 952]
 [931 347 612 217 333]
 [991 218   3 872 463]
 [165 129 409 285 760]
 [733 106 885 227 761]
 [190 448 869 495  33]
 [736 194 710 826 910]
 [771 932 338  94 815]
 [275 975 212 556 290]
 [817 316 305 911 301]
 [867 110 982 228 356]
 [924 558 573 931 231]
 [367  40 943 511 975]
 [801 574  42 555 313]
 [499 707 448 832 472]
 [941  53 541 313 606]
 [ 18 580 257 346 877]
 [923 488 903 739 819]
 [594 473 381 861 602]
 [ 73 929 855 966 423]
 [ 37 300 191 396 459]
 [621 759 449 607 842]
 [979 887 708 959 559]
 [549 843 705 431 948]
 [530 959 123 819  88]
 [887  34 999 334 259]
 [ 42 904  45 308 588]
 [397 486 577 627 336]
 [256 138 496 858 592]
 [918 514 367 258 561]
 [277  62 925 455 243]
 [239 460 501 124 511]
 [137 674 287 326 723]
 [175 851 187 781 120]]
Filtered Array:
[960 200 860 760 190 710 910 290 110  40 580 30